-- ============================================
-- PHOTOGRAPHY STUDIO DATABASE TABLES
-- ============================================

-- 1. STAFF TABLE
CREATE TABLE STAFF (
    STAFFEMAIL VARCHAR2(100) PRIMARY KEY,
    FIRSTNAME VARCHAR2(50) NOT NULL,
    LASTNAME VARCHAR2(50) NOT NULL,
    PHONE VARCHAR2(20),
    ROLE VARCHAR2(50) NOT NULL,
    HIREDATE DATE NOT NULL,
    PAYRATE NUMBER(8,2) NOT NULL,
    STREET VARCHAR2(100),
    CITY VARCHAR2(50),
    STATE VARCHAR2(2),
    ZIP VARCHAR2(10)
);

-- 2. MARKETING_LEAD TABLE
CREATE TABLE MARKETING_LEAD (
    EMAIL VARCHAR2(100) PRIMARY KEY,
    FIRSTNAME VARCHAR2(50) NOT NULL,
    LASTNAME VARCHAR2(50) NOT NULL,
    DATESIGNEDUP DATE NOT NULL,
    INTERESTS VARCHAR2(100)
);

-- 3. CLIENT TABLE
CREATE TABLE CLIENT (
    CLIENTEMAIL VARCHAR2(100) PRIMARY KEY,
    FIRSTNAME VARCHAR2(50) NOT NULL,
    LASTNAME VARCHAR2(50) NOT NULL,
    PHONE VARCHAR2(20),
    STREET VARCHAR2(100),
    CITY VARCHAR2(50),
    STATE VARCHAR2(2),
    ZIP VARCHAR2(10),
    LEADSOURCE VARCHAR2(50),
    MANAGEDBY_STAFFEMAIL VARCHAR2(100) NOT NULL,
    MARKETINGLEAD_EMAIL VARCHAR2(100),
    LAST_SESSION_DATE DATE,
    CONSTRAINT fk_client_staff 
        FOREIGN KEY (MANAGEDBY_STAFFEMAIL) 
        REFERENCES STAFF(STAFFEMAIL),
    CONSTRAINT fk_client_marketinglead 
        FOREIGN KEY (MARKETINGLEAD_EMAIL) 
        REFERENCES MARKETING_LEAD(EMAIL)
);

-- 4. PHOTO_SESSION TABLE
CREATE TABLE PHOTO_SESSION (
    SESSIONID NUMBER(10) PRIMARY KEY,
    SESSIONTYPE VARCHAR2(50) NOT NULL,
    SESSIONDATE DATE NOT NULL,
    SESSIONSTARTTIME VARCHAR2(5),
    SESSIONENDTIME VARCHAR2(5),
    LOCATION VARCHAR2(100),
    PACKAGENAME VARCHAR2(50),
    SESSIONFEE NUMBER(8,2) NOT NULL,
    NOTES VARCHAR2(4000),
    CLIENTEMAIL VARCHAR2(100) NOT NULL,
    DEPOSITPAID NUMBER(8,2) NOT NULL,
    CONSTRAINT fk_session_client 
        FOREIGN KEY (CLIENTEMAIL) 
        REFERENCES CLIENT(CLIENTEMAIL)
);

-- 5. INVOICE TABLE
CREATE TABLE INVOICE (
    INVOICENUMBER NUMBER(10) PRIMARY KEY,
    INVOICEDATE DATE NOT NULL,
    DESCRIPTION VARCHAR2(200),
    SUBTOTAL NUMBER(10,2) NOT NULL,
    TAX NUMBER(10,2) NOT NULL,
    TOTALDUE NUMBER(10,2) NOT NULL,
    BALANCEDUE NUMBER(10,2) NOT NULL,
    PAYMENTRECEIVED NUMBER(10,2) NOT NULL,
    BALANCEDUEDATE DATE,
    CLIENTEMAIL VARCHAR2(100) NOT NULL,
    CONSTRAINT fk_invoice_client 
        FOREIGN KEY (CLIENTEMAIL) 
        REFERENCES CLIENT(CLIENTEMAIL)
);

-- 6. PRODUCT TABLE
CREATE TABLE PRODUCT (
    PRODUCTID NUMBER(10) PRIMARY KEY,
    PRODUCTNAME VARCHAR2(100) NOT NULL,
    COSTPRICE NUMBER(8,2) NOT NULL,
    SALEPRICE NUMBER(8,2) NOT NULL,
    INITIALSTOCKLEVEL NUMBER(10,0) NOT NULL,
    SUPPLIER VARCHAR2(100)
);

-- 7. PHOTO_SESSION_ASSIGNMENT TABLE
CREATE TABLE PHOTO_SESSION_ASSIGNMENT (
    SESSIONID NUMBER(10) NOT NULL,
    STAFFEMAIL VARCHAR2(100) NOT NULL,
    ROLE VARCHAR2(50) NOT NULL,
    CONSTRAINT pk_session_assignment 
        PRIMARY KEY (SESSIONID, STAFFEMAIL),
    CONSTRAINT fk_sa_session 
        FOREIGN KEY (SESSIONID) 
        REFERENCES PHOTO_SESSION(SESSIONID),
    CONSTRAINT fk_sa_staff 
        FOREIGN KEY (STAFFEMAIL) 
        REFERENCES STAFF(STAFFEMAIL)
);

-- 8. INVOICE_LINEITEM TABLE
CREATE TABLE INVOICE_LINEITEM (
    INVOICENUMBER NUMBER(10) NOT NULL,
    PRODUCTID NUMBER(10) NOT NULL,
    QUANTITY NUMBER(5,0) NOT NULL,
    CONSTRAINT pk_invoice_lineitem 
        PRIMARY KEY (INVOICENUMBER, PRODUCTID),
    CONSTRAINT fk_il_invoice 
        FOREIGN KEY (INVOICENUMBER) 
        REFERENCES INVOICE(INVOICENUMBER),
    CONSTRAINT fk_il_product 
        FOREIGN KEY (PRODUCTID) 
        REFERENCES PRODUCT(PRODUCTID),
    CONSTRAINT chk_il_quantity 
        CHECK (QUANTITY > 0)
);

-- Display confirmation
BEGIN
    DBMS_OUTPUT.PUT_LINE('All tables created successfully!');
END;
/